import type { ReportResponse } from '@/types/report'
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from '@/pages/_components/ui/sheet'
import { Badge } from '@/pages/_components/ui/badge'
import { ScrollArea } from '@/pages/_components/ui/scroll-area'
import {
  CalendarRange,
  Clock,
  Wallet,
  ClipboardList,
  AlertTriangle,
  User,
} from 'lucide-react'
import { formatPHP, getMoneyTooltip } from '@/utils/formatPHP'

interface Props {
  report: ReportResponse | null
  onOpenChange: (open: boolean) => void
}

export default function ReportDetailSheet({ report, onOpenChange }: Props) {
  return (
    <Sheet open={!!report} onOpenChange={onOpenChange}>
      <SheetContent className="w-full sm:max-w-md">
        <SheetHeader className="mb-4">
          <SheetTitle className="flex items-center gap-2">
            <CalendarRange className="h-4 w-4 text-zinc-400" />
            {report ? `${report.week_start} – ${report.week_end}` : '—'}
          </SheetTitle>
        </SheetHeader>
        <ScrollArea className="h-[calc(100vh-8rem)] pr-4">
          <div className="flex flex-col gap-6">
            {/* Generated By */}
            <div className="flex flex-col gap-1.5">
              <div className="flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide text-zinc-400 dark:text-zinc-500">
                <User className="h-3.5 w-3.5" />
                Generated By
              </div>
              <div className="flex items-center gap-2">
                <p className="text-sm text-zinc-700 dark:text-zinc-300">
                  {report?.source === 'scheduled'
                    ? '—'
                    : (report?.generated_by_name ?? '—')}
                </p>
                {report && (
                  <Badge
                    variant="outline"
                    className={
                      report.source === 'scheduled'
                        ? 'bg-blue-50 text-xs font-medium text-blue-700 dark:bg-blue-900/30 dark:text-blue-400'
                        : report.source === 'seeded'
                          ? 'bg-amber-50 text-xs font-medium text-amber-700 dark:bg-amber-900/30 dark:text-amber-400'
                          : 'bg-zinc-100 text-xs font-medium text-zinc-600 dark:bg-zinc-800 dark:text-zinc-300'
                    }
                  >
                    {report.source === 'scheduled'
                      ? 'Auto (Monday)'
                      : report.source === 'seeded'
                        ? 'Historical'
                        : 'Manual'}
                  </Badge>
                )}
              </div>
            </div>

            {/* Total Hours */}
            <div className="flex flex-col gap-1.5">
              <div className="flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide text-zinc-400 dark:text-zinc-500">
                <Clock className="h-3.5 w-3.5" />
                Total Hours
              </div>
              <p className="text-sm text-zinc-700 dark:text-zinc-300">
                {report ? `${report.total_hours.toLocaleString()}h` : '—'}
              </p>
            </div>

            {/* Material Cost */}
            <div className="flex flex-col gap-1.5">
              <div className="flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide text-zinc-400 dark:text-zinc-500">
                <Wallet className="h-3.5 w-3.5" />
                Material Cost
              </div>
              <p
                className="text-sm text-zinc-700 dark:text-zinc-300"
                title={
                  report
                    ? getMoneyTooltip(report.total_material_cost)
                    : undefined
                }
              >
                {report ? formatPHP(report.total_material_cost) : '—'}
              </p>
            </div>

            {/* Log Count */}
            <div className="flex flex-col gap-1.5">
              <div className="flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide text-zinc-400 dark:text-zinc-500">
                <ClipboardList className="h-3.5 w-3.5" />
                Logs Submitted
              </div>
              <p className="text-sm text-zinc-700 dark:text-zinc-300">
                {report?.log_count ?? '—'}
              </p>
            </div>

            {/* Incidents */}
            <div className="flex flex-col gap-1.5">
              <div className="flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide text-zinc-400 dark:text-zinc-500">
                <AlertTriangle className="h-3.5 w-3.5" />
                Incidents
              </div>
              {report && report.incident_count > 0 ? (
                <Badge
                  className={
                    report.open_incident_count > 0
                      ? 'w-fit bg-red-100 text-xs font-medium text-red-700 dark:bg-red-900/30 dark:text-red-400'
                      : 'w-fit bg-zinc-100 text-xs font-medium text-zinc-600 dark:bg-zinc-800 dark:text-zinc-300'
                  }
                  variant="outline"
                >
                  {report.incident_count} total
                  {report.open_incident_count > 0
                    ? ` · ${report.open_incident_count} open`
                    : ''}
                </Badge>
              ) : (
                <span className="text-sm text-zinc-400">—</span>
              )}
            </div>
          </div>
        </ScrollArea>
      </SheetContent>
    </Sheet>
  )
}
